// eslint-disable-next-line
export default [
  {
    id: 1,
    read: false,
    img: "avatar-mark-webber.webp",
    name: "Mark Webber",
    action: "reacted to your recent post",
    secondaryLink: "My first tournament today!",
    time: "1m ago",
    postImg: "image-chess.webp",
  },
  {
    id: 2,
    read: false,
    img: "avatar-angela-gray.webp",
    name: "Angela Gray",
    action: "followed you",
    time: "5m ago",
    postImg: "image-chess.webp",
  },
  {
    id: 3,
    read: false,
    img: "avatar-jacob-thompson.webp",
    name: "Jacob Thompson",
    action: "has joined your group",
    primaryLink: "Chess Club",
    time: "1 day ago",
    postImg: "image-chess.webp",
  },
  {
    id: 4,
    read: true,
    img: "avatar-rizky-hasanuddin.webp",
    name: "Rizky Hasanuddin",
    action: "sent you a private message",
    time: "5 days ago",
    message:
      "Hello, thanks for setting up the Chess Club. I’ve been a member for a few weeks now and I’m already having lots of fun and improving my game.",
    postImg: "image-chess.webp",
  },
  {
    id: 5,
    read: true,
    img: "avatar-kimberly-smith.webp",
    name: "Kimberly Smith",
    action: "commented on your picture",
    time: "1 week ago",
    postImg: "image-chess.webp",
  },
  {
    id: 6,
    read: true,
    img: "avatar-nathan-peterson.webp",
    name: "Nathan Peterson",
    action: "reacted to your recent post",
    secondaryLink: "5 end-game strategies to increase your win rate",
    time: "2 weeks ago",
    postImg: "image-chess.webp",
  },
  {
    id: 7,
    read: true,
    img: "avatar-anna-kim.webp",
    name: "Anna Kim",
    action: "left the group",
    primaryLink: "Chess Club",
    time: "2 weeks ago",
    postImg: "image-chess.webp",
  },
];
