// eslint-disable-next-line
export default [
  {
    id: 1,
    img: "avatar-mark-webber.webp",
    name: "Mark Webber",
    action: "reacted to your recent post",
    link: "My first tournament today!",
    badge: true,
    time: "1m ago",
  },
  {
    id: 2,
    img: "avatar-angela-gray.webp",
    name: "Angela Gray",
    action: "followed you",
    badge: true,
    time: "5m ago",
  },
  {
    id: 3,
    img: "avatar-jacob-thompson.webp",
    name: "Jacob Thompson",
    action: "sent you a private message",
    badge: true,
    time: "1 day ago",
  },
  {
    id: 4,
    img: "avatar-rizky-hasanuddin.webp",
    name: "Rizky Hasanuddin",
    action: "reacted to your recent post",
    badge: false,
    time: "5 days ago",
    message: "Hello, thanks for setting up the Chess Club. I’ve been a member for a few weeks now and I’m already having lots of fun and improving my game.",
  },
  {
    id: 5,
    img: "avatar-kimberly-smith.webp",
    name: "Kimberly Smith",
    action: "commented on your picture",
    badge: false,
    time: "1 week ago",
  },
  {
    id: 6,
    img: "avatar-nathan-peterson.webp",
    name: "Nathan Peterson",
    action: "reacted to your recent post",
    link: "5 end-game strategies to increase your win rate",
    badge: false,
    time: "2 weeks ago",
  },
  {
    id: 7,
    img: "avatar-anna-kim.webp",
    name: "Anna Kim",
    action: "left the group",
    link: "Chess Club",
    badge: false,
    time: "2 weeks ago",
  },
];
